[package]
name = "ip-epa127"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "host"
path = "src/bin/host.rs"

[[bin]]
name = "router"
path = "src/bin/router.rs"

[dependencies]
etherparse = "0.16"
ipnet = "2.10.1"
rustyline = "14.0.0"
